variables:
  SERVICE: ddm-iic-web

cache:
  paths:
    - build

stages:
  - analysis

sonarqube:
  tags:
    - sonar-scan
  stage: analysis
  variables:
    SONAR_URL: http://10.64.18.140:9000
    SONAR_ANALYSIS_MODE: publish
  script:
    - /home/sonar-scanner-4.6.2.2472-linux/bin/sonar-scanner
